packages:
  - 'sdk/client'
  - 'sdk/server'
  - 'sdk/checkout'

ignoredBuiltDependencies:
  - '@coinbase/x402'
  - '@reown/appkit'
  - bufferutil
  - esbuild
  - facilitators
  - keccak
  - sharp
  - utf-8-validate
